
package com.ex.hiworld.server.syu;

public class FinalKeyCode {
	public final static int MCU_CANBUS_HEAD = 0xE9;

	public final static int CANBUS_TYPE_NULL	= 0;
	public final static int CANBUS_TYPE_WC1		= 1;//38400
	public final static int CANBUS_TYPE_WC2		= 2;//38400
	public final static int CANBUS_TYPE_WC3		= 3;//19200
	public final static int CANBUS_TYPE_XP1		= 4;//38400
	public final static int CANBUS_TYPE_XP2		= 5;//38400
	public final static int CANBUS_TYPE_RZC1	= 6;//19200
	public final static int CANBUS_TYPE_RZC2	= 7;//38400
	public final static int CANBUS_TYPE_RZC3	= 8;//19200
	public final static int CANBUS_TYPE_RZC4	= 9;//19200
	public final static int CANBUS_TYPE_FYT0	= 10;//38400
	public final static int CANBUS_TYPE_FYT1	= 10;//9600
	public final static int CANBUS_TYPE_FYT2	= 11;//9600
	public final static int CANBUS_TYPE_FYTA	= 10;//?
	public final static int CANBUS_TYPE_DJ1		= 12;//38400

	public static final int KEY_CODE_NULL					= -1;	// 无功能
	public static final int KEY_CODE_POWER					= 0;	// MCU开机键
	public static final int KEY_CODE_NAVI					= 1;	// 导航键
	public static final int KEY_CODE_MODE					= 2;	// 模式键
	public static final int KEY_CODE_PREV					= 3;	// 上一曲
	public static final int KEY_CODE_NEXT					= 4;	// 下一曲
	public static final int KEY_CODE_HOME					= 5;	// 主页
	public static final int KEY_CODE_BACK					= 6;	// 返回键
	public static final int KEY_CODE_VOL_UP					= 7;	// 音量加
	public static final int KEY_CODE_VOL_DOWN				= 8;	// 音量减
	public static final int KEY_CODE_MENU					= 9;	// 菜单
	public static final int KEY_CODE_ALL_APPS				= 10;	// 所有应用
	public static final int KEY_CODE_EJECT					= 11;	// 出仓
	public static final int KEY_CODE_MUTE					= 12;	// 静音
	public static final int KEY_CODE_VA						= 13;	// 语音
	public static final int KEY_CODE_DIM					= 14;	// 背光亮度控制
	public static final int KEY_CODE_RECENT_TASK			= 15;	// 最近任务
	public static final int KEY_CODE_PLAYPAUSE				= 16;	// 播放暂停
	public static final int KEY_CODE_CAMERA					= 17;	// 全景摄像头
	public static final int KEY_CODE_PHONE					= 18;	// 电话
	public static final int KEY_CODE_TONE_PLUS				= 19;	// tone+
	public static final int KEY_CODE_TONE_MINUS				= 20;	// tone-
	public static final int KEY_CODE_BAND					= 21;	// band
	public static final int KEY_CODE_DVD					= 22;	// DVD
	public static final int KEY_CODE_PANORAMA				= 23;	// 全景
	public static final int KEY_RADIO						= 24;	// 收音机
	public static final int KEY_BLACK_SCREEN				= 25;	// 黑屏
	public static final int KEY_CODE_HANG					= 26;	// 挂电话
	public static final int KEY_CODE_FF						= 27;	// 快进
	public static final int KEY_CODE_FB						= 28;	// 快退
	public static final int KEY_CODE_ENTER					= 29;	// 确认
	public static final int KEY_CODE_ROLL_LEFT				= 30;	// 左旋
	public static final int KEY_CODE_ROLL_RIGHR				= 31;	// 右旋
	public static final int KEY_CODE_LEFT					= 32;	// 左
	public static final int KEY_CODE_RIGHT					= 33;	// 右
	public static final int KEY_CODE_UP						= 34;	// 上
	public static final int KEY_CODE_DOWN					= 35;	// 下
	public static final int KEY_CODE_PLAY					= 36;	// 播放
	public static final int KEY_CODE_PAUSE					= 37;	// 暂停
	public static final int KEY_CODE_EQ						= 38;	// EQ
	public static final int KEY_CODE_SEARCH					= 39;	// 搜索
	public static final int KEY_CODE_N1						= 40;	// 1
	public static final int KEY_CODE_N2						= 41;	// 2
	public static final int KEY_CODE_N3						= 42;	// 3
	public static final int KEY_CODE_N4						= 43;	// 4
	public static final int KEY_CODE_N5						= 44;	// 5
	public static final int KEY_CODE_N6						= 45;	// 6
	public static final int KEY_CODE_N7						= 46;	// 7
	public static final int KEY_CODE_N8						= 47;	// 8
	public static final int KEY_CODE_N9						= 48;	// 9
	public static final int KEY_CODE_N0						= 49;	// 0
	public static final int KEY_CODE_NX						= 50;	// *
	public static final int KEY_CODE_NJ						= 51;	// #
	public static final int KEY_CODE_TV						= 52;	// TV
	public static final int KEY_CODE_AUX					= 53;	// AUX
	public static final int KEY_CODE_PLAYER					= 54;	// PLAYER
	public static final int KEY_CODE_CARSETTTING			= 55;	// 车载设置
	public static final int KEY_CODE_TIMESETTINT			= 56;	// 时间设置
	public static final int KEY_CODE_CALI					= 57;	// 屏幕校准
	public static final int KEY_CODE_SYSTEMINFO				= 58;	// 系统设置
	public static final int KEY_CODE_DVR					= 59;	// DVR
	public static final int KEY_CODE_CARUSB					= 60;	// 原车USB
	public static final int KEY_CODE_CARRADIO				= 61;	// 原车收音机
	public static final int KEY_CODE_AIRSHOW				= 62;	// 显示空调信息
	public static final int KEY_CODE_CANBUS					= 63;	// 车辆信息
	public static final int KEY_CODE_SCAN					= 64;	// scan
	public static final int KEY_CODE_REPEAT					= 65;	// 重复
	public static final int KEY_CODE_RANDOM					= 66;	// 随机
	public static final int KEY_CODE_SEEK_UP				= 67;	// seek_up
	public static final int KEY_CODE_SEEK_DOWN				= 68;	// seek_down
	public static final int KEY_CODE_STAND_BY				= 69;	// stand_by
	public static final int KEY_CODE_DISPLAY				= 70;	// DVD功能
	public static final int KEY_CODE_BRIGHT_DEC				= 71;	// 背光减
	public static final int KEY_CODE_BRIGHT_INC				= 72;	// 背光加
	public static final int KEY_CODE_AUDIOSETTING			= 73;  //声音设置
	public static final int KEY_CODE_FM						= 74;  //FM
	public static final int KEY_CODE_AM						= 75;  //AM
	public static final int KEY_CODE_BT_AV					= 76;  //蓝牙音乐
	public static final int KEY_CODE_NC						= 77;  //蓝牙清除,没有功能
	public static final int KEY_CODE_TA						= 78;  //TA功能

    public static final int ACTION_DOWN = 0;
    public static final int ACTION_UP = 1;
}
